'''
<p>She revolutionized the world of celebrity gossip and became one of the most famous women in America by the 1970s. But Hollywood columnist Rona Barrett is largely forgotten in 2016. Nevertheless, the fruits of Barrett\u2019s labors are seen all over television and the internet today. Her influence is felt in every gossipy showbiz blogger, every \u201cconfessional\u201d talk show interview, and every article scrutinizing box office returns. Recently, <i>BuzzFeed</i>\u2019s Anne Helen Petersen caught up with Barrett, who is comfortably retired in California and deeply involved in charity work for the elderly, for a career-spanning retrospective article entitled, appropriately enough, <a href="https://www.buzzfeed.com/annehelenpetersen/all-the-dirt-on-rona-barrett-the-forgotten-gossip-girl?utm_term=.hkP4V8wM2#.ptL3zd1Pp">\u201cGossip Girl.\u201d</a> The story makes a case for Barrett, a woman once known to millions simply as \u201cMiss Rona,\u201d as one of the pivotal figures in entertainment journalism of the previous century.</p>
<div data-type="youtube" contenteditable="false" class="youtube inline size-big crop-16x9" data-youtube-id="cepJ3Dn4Wx8" data-size="big" data-crop="16x9">
<div>
    <img src="//img.youtube.com/vi/cepJ3Dn4Wx8/hqdefault.jpg"></div><span class="caption"></span>
</div>
<p>Born Rona Burstein in Queens in 1936, Barrett spent much of her life suppressing her Jewish heritage, the article reveals. She changed her last name, got her nose fixed, and worked to remove any traces of a Queens accent from her voice. But antisemitism still surrounded her, a lesson she learned early on as the president of Eddie Fisher\u2019s fan club. She overheard the singer making anti-Jewish remarks, and from then on, she no longer worshiped celebrities. That toughness served her well in the 1950s, when she began reporting on the new breed of stars, including Marlon Brando and Natalie Wood, who were then taking over the industry. She managed to leapfrog from magazine work to her own newspaper column to television appearances, finally becoming a regular on ABC\u2019s <i>Good Morning America</i>. Along the way, she cultivated her own flamboyant public persona, adopting her signature, artichoke-shaped, platinum hairdo and getting a customized \u201cMS RONA\u201d license plate for her Rolls-Royce.</p>
<p>While the public loved Barrett for the candor of her reports on the showbiz scene, many of the celebrities themselves did not agree. Ryan O\u2019Neal sent her a live tarantula in the mail. Mia Farrow dumped champagne on her. And an apoplectic Frank Sinatra took to calling her names during his concerts. Barrett\u2019s own bosses and coworkers did not take her seriously, and she had to deal with some outright hostility on the job. Eventually, she saw her career eclipsed by Barbara Walters and Oprah Winfrey, as they followed the trail Barrett herself had blazed. So she walked away from the industry, cancelled her <i>Variety </i>subscription, and didn\u2019t look back, at least not often. She\u2019s comfortable with her legacy and sees how little showbiz has really changed over the decades. \u201cHistory repeats itself,\u201d she tells Petersen. \u201cIt just wears a different dress.\u201d</p>
<div data-type="youtube" contenteditable="false" class="youtube inline size-big crop-16x9" data-youtube-id="32T2cKjgXmg" data-size="big" data-crop="16x9">
    <div><img src="//img.youtube.com/vi/32T2cKjgXmg/hqdefault.jpg"></div><span class="caption"></span></div>
<p><br></p>
'''
